### PR TITLE
Automatically restarts the server after updates

### PR DESCRIPTION
**Pull request by meiamsome**
Implements #111 

My Bash is a bit rusty, so this probably could do with a review by someone more used to it.

### CODE REVIEW

**Comment by tmzasz** [comment]
on my personal copy of the init script all i had to do was add start_service to line 504 after echo "Successfully updated factorio"

**Comment by tacgnol3** [comment]
how can I git pull this specific pull request?

**Comment by Dynamic-Gravity** [comment]
@tacgnol3 do a fork of this repo and then implement the pull request and see if it works.

I'm not so sure if this repo is being maintained anymore.

**Comment by meiamsome** [comment]
@tacgnol3 
You can do this:

    git pull origin pull/112/head

You will then have these changes in your local branch and doing the update will restart factorio automatically.

**Comment by tacgnol3** [comment]
Thanks! Will try at the next update!

**Pull request merged**
